"""empty message

Revision ID: 08c518e84895
Revises: c5f37cf5f094
Create Date: 2024-12-15 16:36:59.703761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08c518e84895'
down_revision: Union[str, None] = 'c5f37cf5f094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SubmissionTable', 'output',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SubmissionTable', 'output',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
