"""empty message

Revision ID: 3b97fb64623a
Revises: 08c518e84895
Create Date: 2024-12-15 16:38:19.036613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b97fb64623a'
down_revision: Union[str, None] = '08c518e84895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SubmissionTable', 'exec_time',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SubmissionTable', 'exec_time',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
