"""empty message

Revision ID: 646f2d7383c6
Revises: aa08d44c01cd
Create Date: 2024-12-14 18:35:05.081615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '646f2d7383c6'
down_revision: Union[str, None] = 'aa08d44c01cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ContestTaskTable_num_key', 'ContestTaskTable', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ContestTaskTable_num_key', 'ContestTaskTable', ['num'])
    # ### end Alembic commands ###
