"""empty message

Revision ID: 910e7ecde897
Revises: e10f6934aea6
Create Date: 2024-11-23 20:48:48.101580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '910e7ecde897'
down_revision: Union[str, None] = 'e10f6934aea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('UserTable', 'is_organizer',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('UserTable', 'is_organizer',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
