"""empty message

Revision ID: 9f76eab531be
Revises: 5b3564c6bca6
Create Date: 2024-11-24 01:54:55.344804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f76eab531be'
down_revision: Union[str, None] = '5b3564c6bca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('GroupTable', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'GroupTable', 'UserTable', ['owner_id'], ['user_id'])
    op.alter_column('UserGroupTable', 'status',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('UserGroupTable', 'status',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'GroupTable', type_='foreignkey')
    op.drop_column('GroupTable', 'owner_id')
    # ### end Alembic commands ###
