"""empty message

Revision ID: aa08d44c01cd
Revises: df7f97b8b727
Create Date: 2024-12-13 15:26:48.203093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa08d44c01cd'
down_revision: Union[str, None] = 'df7f97b8b727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ContestGroupTable',
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['ContestTable.contest_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['GroupTable.group_id'], ),
    sa.PrimaryKeyConstraint('contest_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ContestGroupTable')
    # ### end Alembic commands ###
