"""empty message

Revision ID: ac101c7db672
Revises: 910e7ecde897
Create Date: 2024-11-23 21:19:22.218542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac101c7db672'
down_revision: Union[str, None] = '910e7ecde897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GroupTable',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('group_name')
    )
    op.create_table('u_g_table',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['GroupTable.group_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['UserTable.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('u_g_table')
    op.drop_table('GroupTable')
    # ### end Alembic commands ###
