"""empty message

Revision ID: c5f37cf5f094
Revises: 646f2d7383c6
Create Date: 2024-12-15 15:46:58.344206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5f37cf5f094'
down_revision: Union[str, None] = '646f2d7383c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SubmissionTable',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('language', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('output', sa.String(), nullable=False),
    sa.Column('exec_time', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['ContestTable.contest_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['TaskTable.task_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['UserTable.user_id'], ),
    sa.PrimaryKeyConstraint('submission_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SubmissionTable')
    # ### end Alembic commands ###
