"""empty message

Revision ID: d3cb0196f50c
Revises: 3b97fb64623a
Create Date: 2024-12-15 19:33:55.927524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3cb0196f50c'
down_revision: Union[str, None] = '3b97fb64623a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SubmissionTable', 'exec_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SubmissionTable', sa.Column('exec_time', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
