"""empty message

Revision ID: f798438b1e8b
Revises: d52f6d666760
Create Date: 2024-11-25 21:02:34.587755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f798438b1e8b'
down_revision: Union[str, None] = 'd52f6d666760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TestTable', sa.Column('test_num', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TestTable', 'test_num')
    # ### end Alembic commands ###
